from typing import List, Dict, Any
from google.adk.agents import Agent, LlmAgent, SequentialAgent
from config import Config, logger
import tools

# --- LIFECYCLE HOOKS ---
def hook_before_agent(context: Dict):
    logger.info(f"🎬 ACTION: {context.get('agent_name')} is starting...")

def hook_after_agent(context: Dict, result: Any):
    logger.info(f"✅ CUT: {context.get('agent_name')} finished.")
    return result

# --- 1. SPECIALIZED AGENTS ---

# A. Researcher
researcher_agent = LlmAgent(
    name="researcher",
    model=Config.MODEL_NAME,
    description="Analyzes story ideas and builds the world.",
    instruction="""
    You are a Senior Film Researcher.
    Based on the user's input '{user_request}':
    1. Refine the Logline.
    2. Create Character Bios (Protagonist, Antagonist).
    3. Define the Setting and Tone.
    Output a clean, structured research brief.
    """,
    before_agent=hook_before_agent,
    after_agent=hook_after_agent
)

# B. Screenwriter
writer_agent = LlmAgent(
    name="screenwriter",
    model=Config.MODEL_NAME,
    description="Writes script scenes in Fountain format.",
    instruction="""
    You are a professional Screenwriter.
    CONTEXT: {research_context}
    FEEDBACK HISTORY: {feedback}
    
    Task:
    1. Write (or rewrite) the script scenes.
    2. Use standard screenplay format (Scene Headers, Character Names centered).
    3. Address any feedback provided.
    4. If you think the draft is perfect, use the tool `save_script_to_file`.
    """,
    tools=tools.WRITER_TOOLS,
    before_agent=hook_before_agent,
    after_agent=hook_after_agent
)

# C. Editor (JSON Output for Application Logic)
editor_agent = LlmAgent(
    name="editor",
    model=Config.MODEL_NAME,
    description="Quality Assurance.",
    instruction="""
    You are a strict Script Editor. Review the provided script.
    You must output ONLY valid JSON with the following structure:
    {
        "approved": boolean,
        "score": integer (0-10),
        "critique": "string summary of what needs fixing"
    }
    Do not include markdown formatting like ```json.
    """,
    response_mime_type="application/json",
    before_agent=hook_before_agent
)

# D. Storyboard Artist
storyboard_agent = LlmAgent(
    name="storyboard_artist",
    model=Config.MODEL_NAME,
    description="Visualizes scenes.",
    instruction="""
    You are a Storyboard Artist.
    Read the script provided in the input.
    For the 3 most important visual moments:
    1. Write a scene description.
    2. Call the tool `generate_storyboard_image_mock` for each.
    
    Output a report displaying the images generated by the tool.
    """,
    tools=tools.VISUAL_TOOLS,
    before_agent=hook_before_agent
)

# --- 2. WORKFLOW PATTERNS ---
# (Optional chain if we wanted to automate Research -> Write immediately)
dev_chain = SequentialAgent(
    name="development_chain",
    agents=[researcher_agent, writer_agent],
    description="Develops research and writes first draft."
)