####--- START OF FILE agent.py ---

from typing import Dict, Any, Callable, Union
from google.adk.agents import LlmAgent
from google.adk.runners import Runner
from google.genai import types
from config import Config, logger
import tools
import json

# ============================================================
#  HOOK SYSTEM (Wrapper for ADK Agents)
# ============================================================

class HookedAgent:
    """Wraps an ADK Agent and executes it using a Runner."""

    def __init__(
        self,
        agent: LlmAgent,
        before: Callable[[Dict], None] = None,
        after: Callable[[Dict, Any], Any] = None
    ):
        self.agent = agent
        self.before = before
        self.after = after

    def run(self, context: Union[Dict, str], session_service, session_id: str, user_id: str = "default_user"):
        """
        Executes the agent via the ADK Runner.
        """
        # BEFORE hook
        if self.before:
            hook_ctx = context if isinstance(context, dict) else {"input": context}
            self.before({"agent_name": self.agent.name, **hook_ctx})

        # 1. Prepare Input Message
        if isinstance(context, dict):
            input_parts = []
            for k, v in context.items():
                input_parts.append(f"=== {k.upper()} ===\n{v}")
            input_text = "\n\n".join(input_parts)
        else:
            input_text = str(context)

        # 2. Initialize Runner
        runner = Runner(
            agent=self.agent,
            app_name="agentic-story-studio",
            session_service=session_service
        )

        # 3. Create User Content
        message = types.Content(
            role="user",
            parts=[types.Part(text=input_text)]
        )

        # 4. Run Execution Loop
        events = runner.run(
            user_id=user_id,
            session_id=session_id,
            new_message=message
        )

        # 5. Extract Full Transcript
        full_transcript = []
        
        for event in events:
            # --- CHECK 1: Standard ADK Event (Text) ---
            if hasattr(event, "content") and event.content and event.content.parts:
                for part in event.content.parts:
                    # Capture Text
                    if part.text:
                        full_transcript.append(part.text)
                    
                    # Capture Tool Output (Images)
                    if hasattr(part, "function_response") and part.function_response:
                        try:
                            resp = part.function_response.response
                            if isinstance(resp, dict) and "result" in resp:
                                full_transcript.append(f"\n\n{resp['result']}\n\n")
                        except Exception:
                            pass

            # --- CHECK 2: Raw API Response (Candidates) ---
            elif hasattr(event, "candidates") and event.candidates:
                for candidate in event.candidates:
                    if hasattr(candidate, "content") and candidate.content and candidate.content.parts:
                        for part in candidate.content.parts:
                            # Capture Text
                            if part.text:
                                full_transcript.append(part.text)
                            
                            # Capture Tool Output (Images)
                            if hasattr(part, "function_response") and part.function_response:
                                try:
                                    resp = part.function_response.response
                                    if isinstance(resp, dict) and "result" in resp:
                                        full_transcript.append(f"\n\n{resp['result']}\n\n")
                                except Exception:
                                    pass

        # Join all parts
        result_text = "".join(full_transcript)
        
        # Fallback
        if not result_text:
            result_text = "(No text output generated by agent)"
            logger.warning(f"Agent {self.agent.name} produced no text output.")

        # AFTER hook
        if self.after:
            hook_ctx = context if isinstance(context, dict) else {"input": context}
            result_text = self.after({"agent_name": self.agent.name, **hook_ctx}, result_text)

        return result_text

    @property
    def name(self):
        return self.agent.name


# ============================================================
#  HOOK CALLBACKS
# ============================================================

def hook_before_agent(context: Dict):
    logger.info(f"🎬 ACTION: {context.get('agent_name')} is starting...")

def hook_after_agent(context: Dict, result: Any):
    logger.info(f"✅ CUT: {context.get('agent_name')} finished.")
    return result


# ============================================================
# 1. BASE ADK AGENTS
# ============================================================

researcher_base = LlmAgent(
    name="researcher",
    model=Config.MODEL_NAME,
    description="Analyzes story ideas and builds the world.",
    instruction="""
    You are a Senior Film Researcher.
    Based on the user's provided Story Idea:
    1. Refine the Logline.
    2. Create Character Bios (Protagonist, Antagonist).
    3. Define the Setting and Tone.
    Output a clean, structured research brief.
    """
)

writer_base = LlmAgent(
    name="screenwriter",
    model=Config.MODEL_NAME,
    description="Writes script scenes in Fountain format.",
    instruction="""
    You are a professional Screenwriter.
    The Context, Feedback, and Manager Notes are provided in the input message.
    
    Task:
    1. Write (or rewrite) the script scenes.
    2. Use standard screenplay format (Scene Headers, Character Names centered).
    3. Address any feedback provided.
    4. If you think the draft is perfect, use the tool `save_script_to_file`.
    """,
    tools=tools.WRITER_TOOLS,
)

editor_base = LlmAgent(
    name="editor",
    model=Config.MODEL_NAME,
    description="Quality Assurance.",
    instruction="""
    You are a strict Script Editor. Review the provided script.
    You must output ONLY valid JSON with the following structure:
    {
        "approved": boolean,
        "score": integer (0-10),
        "critique": "string summary of what needs fixing"
    }
    Do not include markdown formatting like ```json.
    """
)

storyboard_base = LlmAgent(
    name="storyboard_artist",
    model=Config.MODEL_NAME,
    description="Visualizes scenes.",
    instruction="""
    You are a Storyboard Artist.
    
    Task:
    1. Read the script scenes.
    2. Select 3 key visual moments.
    3. For EACH moment:
       a. Write a header (e.g. "**Scene 1**").
       b. Call the tool `generate_storyboard_image_mock` with a description.
       
    The tool will output the image. You do NOT need to copy the image URL yourself, the system will display what the tool returns.
    Just ensure you call the tool for every scene you want to visualize.
    """,
    tools=tools.VISUAL_TOOLS,
)


# ============================================================
# 2. HOOKED AGENTS
# ============================================================

researcher_agent = HookedAgent(researcher_base, hook_before_agent, hook_after_agent)
writer_agent = HookedAgent(writer_base, hook_before_agent, hook_after_agent)
editor_agent = HookedAgent(editor_base, hook_before_agent, hook_after_agent)
storyboard_agent = HookedAgent(storyboard_base, hook_before_agent, hook_after_agent)